### ISSUE TITLE
An exception of type 'System.ArgumentNullException' occurred in RazorLight.dll but was not handled in user code: 'Value cannot be null.'

### ISSUE THREAD

**Issue by kulashaker30** [toddams/RazorLight#292] opened 2019-12-06 04:59 UTC
When running this line of codes in .net core 3 (mac) I got this exception (👆)

` var engine = new RazorLightEngineBuilder().UseMemoryCachingProvider().Build();`

I am new to this RazorLight so apology if this exception is kinda obvious to some folks if not most.

**Comment by one-matrix** [comment] 2019-12-06 10:12
me too,
```
Value cannot be null. 
razorLightProject
   at RazorLight.Compilation.RazorTemplateCompiler..ctor(RazorSourceGenerator sourceGenerator, RoslynCompilationService roslynCompilationService, RazorLightProject razorLightProject, RazorLightOptions razorLightOptions)
   at RazorLight.RazorLightEngineBuilder.Build()
```

**Comment by kulashaker30** [comment] 2019-12-06 11:10
> me too,
> 
> ```
> Value cannot be null. 
> razorLightProject
>    at RazorLight.Compilation.RazorTemplateCompiler..ctor(RazorSourceGenerator sourceGenerator, RoslynCompilationService roslynCompilationService, RazorLightProject razorLightProject, RazorLightOptions razorLightOptions)
>    at RazorLight.RazorLightEngineBuilder.Build()
> ```

I got help from this [issue](https://github.com/toddams/RazorLight/issues/258l). Please read the conversation I had from the bottom of the thread. Also, I changed from version 2.0.0-beta2 TO 2.0.0-beta1.

**Comment by Jackuzi** [comment] 2019-12-06 15:12
@one-matrix  @kulashaker30  I can confirm that rolling back to 2.0.0-beta1solved this issue for me too.

**Comment by jzabroski** [comment] 2019-12-06 15:15
It seems this issue is documented here: https://nicedoc.io/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md#preview-3

> * [RESOLVED] Runtime compilation using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation throws an error stating "Cannot find reference assembly": When performing runtime Razor compilation, the application throws an error stating reference assemblies cannot be found. To workaround this, edit the project file and add this following property:
> ```xml
> <PropertyGroup>
>   <PreserveCompilationReferences>true</PreserveCompilationReferences>
> </PropertyGroup>
> ```

@kulashaker30 Are you saying if you use 2.0.0-beta2 and `<PreserveCompilationReferences>true</PreserveCompilationReferences>` the problem is not fixed? I'm a little confused on what you did vs. didn't try.

**Comment by kulashaker30** [comment] 2019-12-06 15:19
> It seems this issue is documented here: https://nicedoc.io/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md#preview-3
> 
> > * [RESOLVED] Runtime compilation using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation throws an error stating "Cannot find reference assembly": When performing runtime Razor compilation, the application throws an error stating reference assemblies cannot be found. To workaround this, edit the project file and add this following property:
> > 
> > ```
> > <PropertyGroup>
> >   <PreserveCompilationReferences>true</PreserveCompilationReferences>
> > </PropertyGroup>
> > ```
> 
> @kulashaker30 Are you saying if you use 2.0.0-beta2 and `<PreserveCompilationReferences>true</PreserveCompilationReferences>` the problem is not fixed? I'm a little confused on what you did vs. didn't try.

@jzabroski Yes, adding `<PreserveCompilationReferences>true</PreserveCompilationReferences>` this in the project file doesn't resolve the issue, unless I use version 2.0.0-beta1

**Comment by jzabroski** [comment] 2019-12-06 15:21
@kulashaker30  What if you add both PreserveCompilationContext and PreserveCompilationReferences?  https://github.com/dotnet/sdk/pull/2800

These knobs drive me insane.

**Comment by kulashaker30** [comment] 2019-12-06 15:23
@jzabroski  `<PropertyGroup>
  <PreserveCompilationReferences>true</PreserveCompilationReferences>
</PropertyGroup>` Yes, those. but no luck, @one-matrix  confirmed it though.

**Comment by mrutter** [comment] 2019-12-06 17:15
I have the same problem with .NET Core 2.2. Right now I solved the issue by adding UseFileSystemProject and pointing to an empty folder:

`
var engine = new RazorLightEngineBuilder()
   .UseFileSystemProject("/TEMP~EMPTY")
   .UseMemoryCachingProvider()
   .Build();
`

**Comment by kulashaker30** [comment] 2019-12-06 17:31
> I have the same problem with .NET Core 2.2. Right now I solved the issue by adding UseFileSystemProject and pointing to an empty folder:
> 
> `var engine = new RazorLightEngineBuilder() .UseFileSystemProject("/TEMP~EMPTY") .UseMemoryCachingProvider() .Build();`

@mrutter We encountered the problem in .net core 3 and version 2.0.0-beta2.

**Comment by jzabroski** [comment] 2021-01-04 23:47
The fix for this is to add a sensible default in RazorLightEngineBuilder.  Either FileSystemRazorProject or EmbeddedResourceRazorProject don't really make sense to me.  We should create a  NoRazorProject that throws if you use its features.

**Comment by jzabroski** [comment] 2021-01-06 01:53
Fixed.  I realized that a lot of people probably got code either from an old README.md or from https://dontpaniclabs.com/blog/post/2018/08/08/using-razor-templates-without-mvc-razorlight/ so I decided the best thing to do here was to default to using dynamic templates if you don't pick a project.

**Closed** 2021-01-06 01:52 UTC
