### ISSUE TITLE
Method not found: 'Void Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_CompactOnMemoryPressure(Boolean)'.

### ISSUE THREAD

**Issue by kiran198910** [toddams/RazorLight#376] opened 2020-09-24 21:20 UTC
Getting error while parsing template as string. There is a bug happened for CreatePhysical. And Error message is Method not found: 'Void Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_CompactOnMemoryPressure(Boolean)'. 

 IRazorLightEngine mail_engine = EngineFactory.CreatePhysical(HostingEnvironment.MapPath("~/Templates"));

I have no idea the reason and how to resolve it.
           

*Information*
 - OS: Windows 10
 - Platform .NET Framework 4.6.1
 - RazorLight version : 1.1.0
  - Visual Studio version : VS2019 [16.7.0]

**Comment by jzabroski** [comment] 2020-09-24 21:34
@kiran198910 Are you really using RazorLight 1.1?

**Comment by kiran198910** [comment] 2020-09-24 22:37
Yes, I am using Razorlight 1.1.0
![Screenshot 2020-09-25 040542](https://user-images.githubusercontent.com/51714857/94207114-8bd1c300-fee4-11ea-813b-bb2b8c9d442a.png)

**Comment by jzabroski** [comment] 2020-09-24 22:42
Use the 2.0.0-beta10 release please.  We're getting very close to an
official non-beta release.

**Comment by kiran198910** [comment] 2020-09-24 23:25
Now I have upgraded RazorLight version to 2.0.0-beta10. I am trying to parse HTML template to string. Here is my code 
` var engine = new RazorLightEngineBuilder()
                            .UseFileSystemProject(HostingEnvironment.MapPath("~/Templates"))
                            .UseMemoryCachingProvider()
                            .Build();

             var model = new { Name = "John Doe" };
             string result = await engine.CompileRenderAsync("View.cshtml", model);`
But Now I am getting error  **"Value cannot be null.Parameter name: operatingAssembly "**. Please advice

**Comment by jzabroski** [comment] 2020-09-24 23:34
On the builder, there is an extension method `SetOperatingAssembly`.  You can set to to `Assembly.GetEntryAssembly()` if that is where you locate your RazorLight assemblies.

**Comment by devssharma** [comment] 2020-09-28 18:23
I am getting bellow error,  do we have any fix of this issue 

Method not found: 'System.Collections.Generic.IList`1<Microsoft.Extensions.Primitives.IChangeToken> Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions.get_ExpirationTokens()'.

**Comment by jzabroski** [comment] 2020-09-28 18:26
@devssharma What version of RazorLight are you using?

**Comment by devssharma** [comment] 2020-09-28 19:23
@jzabroski i am using RazorLight 2.0.0-beta9 in .net core 3.1 project. 
![image](https://user-images.githubusercontent.com/18284303/94476426-17ea3000-01ee-11eb-89af-29e315fa5e28.png)

**Comment by jzabroski** [comment] 2020-09-28 23:36
@devssharma In looking at this more carefully, the issue seems to be that in ASP.NET Core 2.x, they removed this interface, and then put it back but marked it as obsolete before the final release. 

Compare:

1. 2.2 docs: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycacheoptions?view=dotnet-plat-ext-2.2
2. 3.0 docs: no mention of this setting.

**Comment by jzabroski** [comment] 2020-09-28 23:37
@devssharma Can you provide your full stack trace?  We don't directly call this method *directly*, so it seems like you're referencing Microsoft.Extensions.Caching 2.2 in a .netcoreapp3.1 TFM somehow.

**Comment by jzabroski** [comment] 2020-09-28 23:43
See also: https://github.com/toddams/RazorLight/issues/69#issuecomment-604134253 -- previously another user ran into this library and reported their Nuget Package Manager went haywire and it was not RazorLight that caused the issue.  I think that's LIKELY the case here.  But you need to get much, much better at providing repro details.  You're giving me partial stack traces and no PackageReference or TargetFramework xml.

**Comment by devssharma** [comment] 2020-09-29 07:38
@jzabroski  I tried razor parsing in temporary .net core 3.1 console app, it successfully parsing the razor template. but my in actual lambda function (.net core 3.1) not working. 

Error:
Method not found: 'System.Collections.Generic.IList`1<Microsoft.Extensions.Primitives.IChangeToken> Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions.get_ExpirationTokens()'.

Information
OS: Windows 10
Platform .NET Core 3.1
RazorLight version : 2.0.0 beta-9
Visual Studio version : VS2019 [16.7.2]

this is what i have written in my project for razor template parsing.  

Create a function for parsing the razor template.

 async Task<string> RazorParsingString(string tmpl)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            var razorEngine = new RazorLightEngineBuilder()
                 .UseEmbeddedResourcesProject(assembly, "OrderComponent") // OrderComponent is a project name
                 .UseMemoryCachingProvider()
                 .Build();

            string sqlTmplt = tmpl;


            string sql = await razorEngine.CompileRenderStringAsync("templateKey", sqlTmplt, new { OrderID = "123" });

            return sql;
        }


and i am calling above function from actual lambda function. looks like.

public JObject Process(JObject input, ILambdaContext context)
        {
            context.Logger.LogLine("Get Request\n");
            string sql = string.Empty;

            string tmpl = "select* from OrderTable Where OrderID = @Model.OrderID";
            context.Logger.LogLine(tmpl);
            Task.Run(async () => { sql = await RazorParsingString(tmpl); }).Wait();

            context.Logger.LogLine(sql);
.......


my requirement is just parse the razor template in .NET core 3.1 version. please help me on this

**Comment by jzabroski** [comment] 2020-09-29 14:29
Hi - I don't think I have the time to debug why this won't work on AWS Lambda.  Maybe you can open a support request with AWS as to why when you convert a console app to a lambda app, all of a sudden it stops working?  This doesn't sounds like a RazorLight problem, and AWS support is pretty good.  If they do give you good feedback, I would appreciate it if you could share what they tell you so others benefit.

That said, you probably shouldn't use the ReadyToRun flag with RazorLight, as it dynamically loads dependencies.

**Comment by jzabroski** [comment] 2020-11-11 17:17
@devssharma Did you ever get any help from AWS Support on this?

**Comment by devssharma** [comment] 2020-11-16 18:49
@jzabroski My problem was resolved with existing library so I didn't contacted them. 

Thank you so much for help on this.

**Closed** 2020-11-16 19:05 UTC
Labels: awaiting-customer-response

**Comment by eralston** [comment] 2021-02-28 15:02
Apologies poking the sleeping dog here, but this is literally the only Google result for this issue:

I am now receiving this same error as a regression bug in my project...

![image](https://user-images.githubusercontent.com/636858/109422913-57ca6480-7992-11eb-95f4-07d72c0c1a0e.png)

Except in my case it's in an Azure Function (.Net Core 3.1 using RazorLight 2.0.0-rc.2) that was previously working properly. I have the following code (which again, was working for months up to a short-time ago):

```
public static void Init(Assembly entryAssembly, Assembly viewAssembly, string rootNamespace)
        {
            Engine = new RazorLightEngineBuilder()
                                .SetOperatingAssembly(entryAssembly)
                                .UseEmbeddedResourcesProject(viewAssembly, rootNamespace)
                                .UseMemoryCachingProvider()
                                .Build();
        }

public async Task<string> RenderAsync<TModel>(string viewName, TModel model)
        {
            string result = await Engine.CompileRenderAsync(viewName, model);
            return result;
        }
```

I would welcome any insight. I will likely go into jumping through past versions now and if I find a solution, I will post it here in the hopes that future generations with not suffer the same fate.
