### ISSUE TITLE
CompileRenderAsync fails to render very long htmls

### ISSUE THREAD

**Issue by g0nP** [toddams/RazorLight#261] opened 2019-07-10 13:43 UTC
**Describe the bug**
I'm using Razorlight to render HTML from the server. I have a view with 2 partial views inside.
One partial view renders static HTML, while the other iterates through a collection and renders html for every item in it.

When the collection has many items (in my tests, 10 or more), the string returned from _CompileRenderAsync_ doesn't include the second partial view that iterates through the collection.

It doesn't throws any exception, it just renders everything but the partial view that depends on the collection.

**To Reproduce**

I have implemented this code, following the example on GitHub:

```
var engine = new RazorLightEngineBuilder()
          .UseFilesystemProject("physical-path-to-Views-folder")
          .UseMemoryCachingProvider()
          .Build();

var html = await engine.CompileRenderAsync("Report.cshtml", resultReport);
```
**Report.cshtml** has 2 partial views:

```
@inherits RazorLight.TemplatePage<MyAssembly.Data.Model.ResultReport>
@model MyAssembly.Data.Model.ResultReport

@{
     await IncludeAsync("Partial/_summary.cshtml", Model);
     await IncludeAsync("Partial/_riskReport.cshtml", Model);
}
```
**_summary.cshtml** shows static information from some properties of the model, while **_riskReport.cshtml** iterates through a collection of risks:

```
<div>
	@foreach (var risk in Model.Risks)
	{
	     <div class="@risk.Level">
		<div class="title-container"><h2 class="title">@risk.Title</h2><h3 class="level">@risk.Level</h3></div>
		<div>@Raw(risk.Description)</div>
	     </div>
	}
</div>
```

**Expected behavior**
It should render html with a Summary Section (_summary.cshtml) and a list of Risks (_riskReport.cshtml).
When the list of Risk has many items, it only renders the Summary Section.

**Information (please complete the following information):**
 - OS: Windows 7
 - Platform Net. Core 2.1
 - RazorLight version 2.0.0-beta1
 - Visual Studio version Visual Studio 2017

**Comment by g0nP** [comment] 2019-07-10 16:54
**UPDATE:**

The error mentioned above happens when I use the NuGet Package.
I have tried downloading the project and manually adding it to my Application and now it works like a charm.
However I cannot go that way. I need it to be a NuGet package.

The difference I've noticed is that when using the NuGet package, the following code:

```
var engine = new RazorLightEngineBuilder()
          .UseFilesystemProject("physical-path-to-Views-folder")
```

has the method _UseFilesystemProject_ with _system_ in lower case.
However when I manually add the project downloaded from GitHub, the method is _UseFileSystemProject_ with _System_ starting with capital letter.

Maybe an update is missing in the NuGet package?

**Comment by matt-downs** [comment] 2019-08-23 00:14
Had this same issue when trying to render a property from the view model over 80 times within a partial. 

Below is some minimal code that replicates the issue: 
[RazerLight-test.zip](https://github.com/toddams/RazorLight/files/3532346/RazerLight-test.zip)

**Comment by jzabroski** [comment] 2019-11-21 16:06
@matt-downs Is this a Duplicate of #134?  Thanks for the repro.  I'll merge it as a test case.

**Comment by jzabroski** [comment] 2019-11-21 16:48
@matt-downs  I tried to repro your issue and could not,  what am I missing?

**Comment by jzabroski** [comment] 2019-11-21 19:27
This is fixed by https://github.com/toddams/RazorLight/commit/0dbc5e1d174411530c3ab81db94dfc3444dd4a4d

**Closed by jzabroski** 2019-11-21 19:27 UTC
