### ISSUE TITLE
2.0.0-beta2 version is not available in nuget

### ISSUE THREAD

**Issue by IKamyshew** [toddams/RazorLight#281] opened 2019-11-22 10:36 UTC
According to the readme latest nuget is:
Install-Package RazorLight -Version 2.0.0-beta2

But the latest version is 2.0.0-beta1
https://www.nuget.org/packages/RazorLight/

Install-Package : NU1102: Unable to find package RazorLight with version (>= 2.0.0-beta2)
  - Found 16 version(s) in nuget.org [ Nearest version: 2.0.0-beta1 ]

**Comment by jzabroski** [comment] 2019-11-22 13:49
Correct.  @toddams is going to release the package to Nuget soon.  We just fixed several issues in 2.0.0-beta2 and merged it two days ago.  The README.md was updated ahead of the push to Nuget.

**Comment by jzabroski** [comment] 2019-11-22 16:00
I got nuget.org collaborator access from Ivan this morning.  Trying to figure out how to upload the new RazorLight package as a collaborator.

**Comment by RedX2501** [comment] 2019-11-22 19:42
Is there a changelog with all the bugs fixed?

**Comment by jzabroski** [comment] 2019-11-22 19:51
Not a professional one.  Here is `git commit --since "12/22/2017"` through October 31, 2019.  Doesn't include @gjunge 's fixes.

If you want to help consolidate this into a changelog, that would be sweet.

```
commit fa1308a696b20b6de216acf24af8f0fc189212ab
Author: John Zabroski <johnzabroski@gmail.com>
Date:   Thu Oct 31 21:05:55 2019 -0400

    Updated sandbox
    
    Need to follow-up with @toddams on why the sandbox isn't buildable.

commit 0912224edbcb044f11eed617ef8d624ff47c6b5f
Author: John Zabroski <johnzabroski@gmail.com>
Date:   Thu Oct 31 21:05:26 2019 -0400

    chore: Upgrade Pose to 1.2.1
    
    Eliminate compiler warning about Mono.Reflection

commit ff6f6f7e32e30f9b0af0475a66d28db4da6eb7ae
Merge: 4de9722 f9f15f3
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Thu Aug 1 14:35:58 2019 +0300

    Merge pull request #266 from lars-nielsen/implement-support-for-conditional-attributes
    
    Support conditional attributes

commit f9f15f300dcf596257f2685a07f8c86d8fe67216
Author: Lars Nielsen <nellemandela@gmail.com>
Date:   Thu Aug 1 13:33:19 2019 +0200

    Support conditional attributes
    
    Fixes #265

commit 4de9722083323952ebcd394a6f96298d864c9ff8
Merge: 43e4237 ab2f8ac
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Thu Aug 1 14:10:01 2019 +0300

    Merge pull request #264 from lars-nielsen/implement-support-for-local-functions
    
    Enable TemplateTargetExtension

commit ab2f8ac1bf9ae74210126022e4e6fb832b8700ce
Author: Lars Nielsen <nellemandela@gmail.com>
Date:   Thu Aug 1 11:46:36 2019 +0200

    Enable TemplateTargetExtension
    
    Fixes #236

commit 43e4237150b2443c3e65fadf25371287d1d3a7c0
Merge: 36ad2b9 2a9745e
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Thu Aug 1 12:11:23 2019 +0300

    Merge pull request #251 from RedX2501/disable_encoding
    
    Add option to builder to globally disable encoding.

commit 36ad2b9a1498c74364fd9a3c4ad39e462c17e637
Merge: 3bf5b82 78d374d
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Thu Jul 11 13:41:46 2019 +0300

    Merge pull request #260 from kevinwell/patch-1
    
    Fix typo

commit 78d374d4cdcb3e4620224aa1c0e2aa6bea1cd6ca
Author: Kevin Well <kevinwell13@gmail.com>
Date:   Fri Jun 21 14:25:54 2019 +1000

    Fix typo

commit 2a9745ee2689d46eb96f3174d45a56ac6ad86081
Author: Guilherme Bufolo <guibufolo+git@gmail.com>
Date:   Sat Apr 6 12:07:44 2019 +0200

    Add option to builder to globally disable encoding.
    
    This is very conventient when you are using the engine
    to generate other things then HTML pages.
    For example C# code.

commit 3bf5b823aa0eacbb920258524053cae75e8ddb93
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Wed Feb 13 23:38:21 2019 +0200

    Update bug_report.md

commit f4e4a329b66c65944a8a8bfc720d25a38b491858
Merge: 346a66e f1117eb
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Wed Feb 13 22:25:21 2019 +0200

    Merge pull request #243 from coxp/feature/1
    
    Add support for nested anonymous models

commit 346a66e0b5d1ee1d1565be9d8483be7da152b2c4
Merge: 7de0c34 7a4b014
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Wed Feb 13 22:24:37 2019 +0200

    Merge pull request #242 from coxp/bugfix/1
    
    Fix infinite loop when using separate compile and render steps

commit f1117eb95074884465d7964acb6115797dded84e
Author: Paul Cox <github@coxp.co.uk>
Date:   Fri Feb 8 15:57:10 2019 +0000

    Add support for nested anonymous models

commit 7a4b0148407a23432402fa2734697354cb5cf7a6
Author: Paul Cox <github@coxp.co.uk>
Date:   Fri Feb 8 15:45:32 2019 +0000

    Fix infinite loop when using separate compile and render steps

commit 7de0c347e5e8f9bf972ce71636abf4405048eac0
Merge: 744f545 a64f034
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Tue Nov 13 12:57:04 2018 +0200

    Merge pull request #233 from ogaudefroy/template-name-not-displayed-when-cannot-be-loaded
    
    Fixed key not used & fixed typo.

commit a64f03429e3e59a4c92843ed8f47eb4012f283da
Author: Roman <rfever@gmail.com>
Date:   Tue Nov 13 11:36:00 2018 +0100

    Update tests/RazorLight.Tests/Generation/RazorSourceGeneratorTest.cs
    
    Co-Authored-By: ogaudefroy <gaulive@gmail.com>

commit ed4fd3f1c37819fb37e38fe80337932689735566
Author: ogaudefroy <ogaudefroy@vente-privee.com>
Date:   Tue Nov 13 11:22:18 2018 +0100

    Fixed key not used & fixed typo.

commit 744f545227083f17c63bcdef989bd5c2017ef53b
Merge: 7c66252 973147b
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Tue Jul 3 12:03:21 2018 +0300

    Merge pull request #198 from Rizzen/patch-1
    
    Fixed Typo

commit 973147bac76458e1450aac8b785f23b7ec4fd91d
Author: Mark <onemangd@gmail.com>
Date:   Sat Jun 23 14:27:04 2018 +0300

    Fixed Typo

commit 7c66252fafcb565bf59c26fcbedd2bb4455ad103
Merge: f56e3b9 0f393df
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Thu Jun 14 08:49:11 2018 +0300

    Merge pull request #193 from thundercraker/FixErrorMessage
    
    Added a message to the exception that occurs when sections are ignored

commit 0f393dfbdb39f32b1467ae27f4b25145664cd83c
Author: Yumashish Subba <yumashish.subba@bitflyer.com>
Date:   Thu Jun 14 12:20:34 2018 +0900

    Added a message to the exception that occurs when sections are ignored

commit f56e3b9ec3b89e967ed2224ea2b86fe0fca6abb4
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 19:34:19 2018 +0300

    Revert "Change .net core to 2.1 on travis"
    
    This reverts commit 965efe21e35d791f86cec3351e9a1d43e1698eef.

commit 965efe21e35d791f86cec3351e9a1d43e1698eef
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 19:32:24 2018 +0300

    Change .net core to 2.1 on travis

commit 2bd37caa92e1f65762aeb8067fa8cfadafa25fdb
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 19:26:52 2018 +0300

    Fix rawString

commit 3a827169d98442bbddb85de9ada8fb034b8c632f
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 19:15:03 2018 +0300

    Attempt to fix Travis

commit b62650fd81a87aa86f9bedd5a75252d80fd23595
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 13:28:57 2018 +0300

    Add build error to Obsolette methods

commit 26e19d8c1a965c73b1a8d7dec1074cbb79bf3200
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 13:18:48 2018 +0300

    Postmerge fixes

commit 56719c357c2de16f42d696a381ca0acc2fe3dcd3
Merge: af07fb7 d0a4cc3
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 13:15:41 2018 +0300

    Merge branch 'mscrivo-master'

commit d0a4cc3dd49f29565adcf849179901440e45fe48
Merge: af07fb7 f0f5e50
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 13:15:23 2018 +0300

    Merge branch 'master' of https://github.com/mscrivo/RazorLight into mscrivo-master
    
    # Conflicts:
    #       src/RazorLight/EngineFactory.cs
    #       src/RazorLight/RazorLightEngineBuilder.cs
    #       src/RazorLight/RazorLightOptions.cs
    #       tests/RazorLight.Tests/Compilation/DefaultMetadataReferenceManagerTest.cs

commit af07fb7b35358854672e8ee83ce593627e2d6907
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 13:08:08 2018 +0300

    Add more tests for razortemplatecompiler

commit 9309a1850e31fbdff34637e9c7b83eb66abf0204
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 12:52:33 2018 +0300

    Throw TemplateNotFound exception when projectItem not exist

commit 32472d5a20b2905f9bdfb3387a43718240d508d5
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 12:37:01 2018 +0300

    Add RazorTemplateCompiler unit tests

commit 574dac60b0f69979db2aeefcb233a80a4601eeba
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 12:36:46 2018 +0300

    Check constructor input on RazorTemplateEngine and expose internal cache for testing

commit 305736221f75af6fa3d90d045af81ee45e0b0bde
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 12:36:09 2018 +0300

    Fix DI test

commit d25aa609a1b294d8ba14f5fe84da15be9d23985d
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 12:35:46 2018 +0300

    Allow RootNamespace be null on RazorLightEngineBuilder

commit 29c024bfc5e3cbff409ab47dcfa88e581b7849ce
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 12:00:18 2018 +0300

    Fix sample project

commit 605b03f8a42ce4149dcd5f465174f721eb63e3ee
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 11:52:36 2018 +0300

    Avoid key normalization when rendering string

commit 30b8cfa3c2b9c5097c92dca5e5bf1da75dbfab62
Merge: 111c694 2ac009e
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 01:22:30 2018 +0300

    Merge branch 'master' of https://github.com/toddams/RazorLight

commit 111c69403dd6169aab45b3760d73edcc28f21927
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 01:21:28 2018 +0300

    #107 - Embedded project can now accept assembly + rootnamespace as a string

commit 153fc12dd2c0e1e23816e6b643dea6ff0e06a971
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 10 01:20:40 2018 +0300

    #123 - Create engine handler. Share template model with layout

commit 2ac009e017c3daf73b436275080f8ddde3c438f9
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Fri Jun 8 19:14:54 2018 +0300

    Update issue templates

commit 8f93e838a7893be2c1a0202705b1fc97828593cd
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Fri Jun 8 19:12:45 2018 +0300

    Update issue templates

commit ea475ebefbd397596290af8481ef1fd76f9d870e
Author: toddams <toddams@gmail.com>
Date:   Fri Jun 8 19:04:30 2018 +0300

    Update compilation tests

commit 915ec6dc8d83865d2af074efd64dce3d53897c69
Author: toddams <toddams@gmail.com>
Date:   Fri Jun 8 18:43:20 2018 +0300

    Fix race condition  compilation bug

commit 0e2f037ff9917767e3c57087e2072093d5b313d8
Author: toddams <toddams@gmail.com>
Date:   Thu Jun 7 20:22:34 2018 +0300

    Extract TemplateCompiler interface

commit 7db20ce36940d5ecd3046d0c9a288e637e6013f0
Author: toddams <toddams@gmail.com>
Date:   Thu Jun 7 20:20:00 2018 +0300

    Correct test asserts

commit dc190498a78df36aee445cbc54bd3dc6c2e23e6e
Author: toddams <toddams@gmail.com>
Date:   Thu Jun 7 20:19:19 2018 +0300

    Comment code for precompiled project

commit ab7606ea11671b9e6674eba088b7bd783fd81bad
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 22:29:02 2018 +0300

    Completely rework template compilation

commit 0b4366b555c55b331e4b21099431ef38a469f7ba
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 22:27:16 2018 +0300

    Add race condition tests

commit 837a19ed1e6fa24635d8c4b1a444b88e4b1ee211
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 22:23:46 2018 +0300

    Remove EngineFactory

commit 5a9bfc09c0aa6dff22da18d6a26583f5a5981968
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 22:22:27 2018 +0300

    Razor 2.1 upgrade fixes

commit d3394d2c981f452e3e799a869916864af153fce7
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 20:44:38 2018 +0300

    Remove obsolette classes

commit 8b9521c4f1e22c30db1856f0487b7eb9e805ee56
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 20:44:05 2018 +0300

    Upgrade nuget packages to 2.1 and Tests SDK

commit 0dbc5e1d174411530c3ab81db94dfc3444dd4a4d
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 17:54:20 2018 +0300

    #134 - Fix IncludeAsync rendering issues

commit ddaa20b961111d017c90a093e01c66ee5b714137
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 16:53:09 2018 +0300

    Sandbox

commit 38d01dcfe495bac6cc612e6a5dd1dff546c51900
Merge: 8cb127e 5abf7b4
Author: toddams <toddams@gmail.com>
Date:   Sun Jun 3 15:08:56 2018 +0300

    Merge branch 'master' of https://github.com/toddams/RazorLight

commit 5abf7b40b741b8b5a3dbb4151ae973a3d6e1eddc
Merge: c886721 5729982
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Sun Jun 3 14:54:14 2018 +0300

    Merge pull request #186 from cacodev/patch-1
    
    Fixing typo in readme

commit 5729982904c19247917c98c42d3a07dd0361d87c
Author: Casey Collins <Caseyc585@users.noreply.github.com>
Date:   Mon May 21 16:30:23 2018 -0400

    Fixing typo in readme

commit 8cb127e70ff4e9fd1bab0c2ac322a99a839a4c44
Merge: adbb0bf c886721
Author: toddams <toddams@gmail.com>
Date:   Sun May 13 17:33:45 2018 +0300

    Merge branch 'master' of https://github.com/toddams/RazorLight

commit f0f5e50b7f2d6adfd8e430edbd2c0deffe5d1171
Author: Michael Scrivo <mscrivo@gmail.com>
Date:   Fri May 4 14:23:58 2018 -0400

    This fixes toddams/RazorLight#172

commit 5ad6999b8217ba503b868ed5c74b81575662cc4e
Author: Michael Scrivo <mscrivo@gmail.com>
Date:   Wed May 2 17:06:27 2018 -0400

    Add ability to exclude assemblies from metadataReferences
    
    There are some cases where assemblies cannot be loaded even by providing the
    additional metadata reference.  They usually aren't needed anyway, and this provides
    for a mechanism to exclude them.

commit c88672114887659311b23c05d7d57e0e0b1dadb6
Merge: 669cb74 2e70e94
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Tue Apr 24 13:22:58 2018 +0300

    Merge pull request #178 from ReinisV/master
    
    fixed ArgumentException in AddDynamicTemplates, removed unnecessary IsNullOrEmpty check in RawString

commit 2e70e94ed208c5083225d7131e748b6bcd6e25d4
Author: Reinis Vesers <reinis.vesers@accenture.com>
Date:   Tue Apr 24 11:21:48 2018 +0300

    fixed ArgumentException("An item with the same key has already been added.") exception and removed unnecessary IsNullOrEmpty check

commit adbb0bf5aadbfcdc771be538cdb60a76623eb524
Merge: 8d796f9 669cb74
Author: toddams <toddams@gmail.com>
Date:   Sun Mar 18 14:10:21 2018 +0200

    Merge remote-tracking branch 'origin/master'

commit 8d796f97d9db0bf1a79478546ae0fbf13ad34d42
Author: toddams <toddams@gmail.com>
Date:   Sun Mar 18 14:10:09 2018 +0200

    Revert "UrlHelpers attempt"
    
    This reverts commit 7e0f19203f753864a7dc2e8f1c06d7ae8eaa229d.

commit 7e0f19203f753864a7dc2e8f1c06d7ae8eaa229d
Author: toddams <toddams@gmail.com>
Date:   Sun Mar 11 17:40:31 2018 +0200

    UrlHelpers attempt
    
    First attempt to add HtmlHelper classes
    
    Add IViewContextAware

commit 669cb741998b6248d7ccfa3f9da2d25acdeaa2f8
Merge: 10aa5a4 1086a97
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Mon Mar 12 23:34:16 2018 +0200

    Merge pull request #159 from colinbull/master
    
    Fix based on @glikoz solution

commit b020c1f93ef539815125d8ce86a7e274d21bfad8
Merge: 8c20408 10aa5a4
Author: toddams <toddams@gmail.com>
Date:   Sun Mar 11 12:24:54 2018 +0200

    Merge branch 'master' of https://github.com/toddams/RazorLight

commit 1086a9745936b14db923005fdd514111c18a4100
Author: Colin Bull <colinbul@googlemail.com>
Date:   Wed Feb 28 14:09:27 2018 +0000

    Fix based on @glikoz solution

commit 10aa5a4cd72f44d0956ac29d6484267afac184d4
Merge: caba19a 26c2e14
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Wed Feb 14 14:53:34 2018 +0200

    Merge pull request #152 from KorsG/patch1
    
    Extension overload to FileSystemRazorProject

commit caba19a1cc6862dd551518d8fd4ee5511735f6e6
Merge: 4ec8214 f1a4c6d
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Wed Feb 14 14:52:43 2018 +0200

    Merge pull request #153 from KorsG/patch2
    
    Fixed MemoryCachingProvider file naming.

commit f1a4c6dc9e274bdce765d418ae711bf8c1d89823
Author: Morten Korsgaard <morten@korsg.dk>
Date:   Sun Feb 11 18:45:04 2018 +0100

    Renamed DefaultCachingProvider.cs file to be the same as the class ~ MemoryCachingProvider.cs.

commit 26c2e149e4e5499859f65b0fc7bbab5a5b28c307
Author: Morten Korsgaard <morten@korsg.dk>
Date:   Sun Feb 11 18:33:59 2018 +0100

    Added constructor overload for the Extension property to FileSystemRazorProject. Also added overload to the builder.
    
    It makes the functionality more discoverable in my opinion :-)

commit f19302a853d2600fb0fe3f02fd671166dd1fd20a
Author: Morten Korsgaard <morten@korsg.dk>
Date:   Sun Feb 11 18:30:16 2018 +0100

    Changed casing on "UseFileSystemProject" to be the same as FileSystemProject class (uppercased S in system).

commit 8c20408bb8ef718e90dcd8c4ad3dba37b6b081e2
Author: toddams <toddams@gmail.com>
Date:   Sat Jan 27 10:10:50 2018 +0200

    Add caching provider to Options

commit 4ec82147f5e761214d0c27086c69293991293917
Merge: 3e4fc30 277ad12
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Thu Jan 25 09:50:14 2018 +0200

    Merge pull request #146 from rshillington/master
    
    Corrected QuickStart code sample for rendering a compiled template

commit 277ad1252ca26f51c37a4669b0cf40ca2762bb28
Author: Ralph Shillington <ralph.shillington@feenics.com>
Date:   Wed Jan 24 15:46:56 2018 -0500

    Corrected QuickStart code sample for rendering a compiled template

commit 3e4fc30e8d509c3f73ebf1917275b698e594dd80
Merge: 8c0e769 2693b93
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Thu Jan 11 18:24:46 2018 +0200

    Merge pull request #138 from deckertron9000/master
    
    Fixing two occurences where viewBag was not passed correctly.

commit 2693b932775480b25063bda470339c7e39654d37
Author: William Decker <wdecker@edgenet.com>
Date:   Thu Jan 11 08:20:36 2018 -0600

    Fixing two occurences where viewBag was not passed correctly.

commit 8c0e769a9851532bef1437183683fc7f7e57265e
Merge: c2ab9ef dc67a41
Author: Ivan Balan <toddams@users.noreply.github.com>
Date:   Sun Dec 24 20:39:14 2017 +0200

    Merge pull request #128 from GoodGoodJM/master
    
    Remove unnecessary semicolon

commit dc67a4102a0dbca1aa5bb9f7ba870b4117012006
Author: = <=>
Date:   Mon Dec 25 02:44:03 2017 +0900

    Modify README.md

commit 61f91b841d57bce81265272c5a341730a761eec4
Author: GoodGoodMan <gjwnsan9420@gmail.com>
Date:   Mon Dec 25 01:59:19 2017 +0900

    Update README.md
```

**Comment by RedX2501** [comment] 2019-11-22 19:52
I tried checking out the commit for 2.0.0-beta2 and I can't seem to find it. What's the name?

**Comment by jzabroski** [comment] 2019-11-22 19:52
It's the head of the master branch

**Comment by jzabroski** [comment] 2019-11-22 19:53
Sorry, I should have been more precise: https://github.com/toddams/RazorLight/commit/7d5a3b041a94ee1cde8bc7dff307beeec823c6bb

**Comment by RedX2501** [comment] 2019-11-22 19:56
If you have already decided that that will be the nuget package maybe you should tag it.

**Comment by jzabroski** [comment] 2019-11-22 20:01
I don't think tags are a good idea.  Next step would be to adopt either GitVersion, GitInfo, or Nerdbank.GitVersioning for predictable, consistent build version numbers.  If you're unfamiliar with these, the basic idea is tags are not reliable, and the closer you can get to tracing a build to an entire tree of commits, the better your versioning scheme is.

**Comment by mattwendels** [comment] 2019-11-22 20:07
There’s a version compiled for .Net Core 3.0 here if you’re desperate and can’t wait for the official package :)

https://www.nuget.org/packages/RazorLight.NetCore3/

**Comment by RedX2501** [comment] 2019-11-22 20:09
Not at all. I'm trying to reproduce a bug I have and thought I'd try the newest version before posting it. Maybe it is gone :)

**Comment by x10an14** [comment] 2019-11-26 10:37
Hi! =)

Any update (or ETA you feel comfortable sharing - with my solemn vow not to hold you to it!) on the nuget.org update? =D

Would be an awesome fit for my `netcoreapp3.0` project if it only supported said standard!

**Comment by jzabroski** [comment] 2019-11-26 12:54
I hope to do it today. I've never actually manually uploaded a package to
nuget.org and plan to do it manually and was waiting on a coworker who has
done it manually to come back from vacation.

**Comment by x10an14** [comment] 2019-11-26 13:28
Thanks! =)

**Comment by Inurias** [comment] 2019-11-27 15:08
Still not on nuget :(

**Comment by jzabroski** [comment] 2019-11-27 16:18
I just pushed it.  Sorry for the delay.  I hope I didn't publish it incorrectly; note that it could take up to one hour to be officially published:

https://www.nuget.org/packages/RazorLight/2.0.0-beta2

**Closed** 2019-11-27 16:19 UTC
